# Generated by Django 5.0.3 on 2024-04-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20240417_1821'),
    ]

    operations = [
    ]
