# Generated by Django 5.0.3 on 2024-04-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(choices=[('+1', 'USA'), ('+995', 'Georgia')], default='+995', max_length=10),
        ),
    ]
