# Generated by Django 5.0.3 on 2024-04-21 09:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa Romeo'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Bugatti', 'Bugatti'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Citroën', 'Citroën'), ('Dodge', 'Dodge'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Genesis', 'Genesis'), ('GMC', 'GMC'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Infiniti', 'Infiniti'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Lamborghini', 'Lamborghini'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('Maserati', 'Maserati'), ('Mazda', 'Mazda'), ('McLaren', 'McLaren'), ('Mercedes-Benz', 'Mercedes-Benz'), ('MINI', 'MINI'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Peugeot', 'Peugeot'), ('Porsche', 'Porsche'), ('RAM', 'RAM'), ('Rolls-Royce', 'Rolls-Royce'), ('Saab', 'Saab'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo')], max_length=100)),
                ('car_model', models.CharField(choices=[('Acura', [('ILX', 'ILX'), ('MDX', 'MDX'), ('RDX', 'RDX'), ('RLX', 'RLX'), ('TLX', 'TLX')]), ('Alfa Romeo', [('Giulia', 'Giulia'), ('Stelvio', 'Stelvio'), ('4C', '4C')]), ('Aston Martin', [('DB11', 'DB11'), ('DBS Superleggera', 'DBS Superleggera'), ('Vantage', 'Vantage'), ('Vanquish', 'Vanquish')]), ('Audi', [('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('A8', 'A8'), ('Q3', 'Q3'), ('Q5', 'Q5'), ('Q7', 'Q7'), ('Q8', 'Q8'), ('TT', 'TT'), ('R8', 'R8'), ('e-tron', 'e-tron')]), ('Bentley', [('Bentayga', 'Bentayga'), ('Continental GT', 'Continental GT'), ('Flying Spur', 'Flying Spur'), ('Mulsanne', 'Mulsanne')]), ('BMW', [('1 Series', '1 Series'), ('2 Series', '2 Series'), ('3 Series', '3 Series'), ('4 Series', '4 Series'), ('5 Series', '5 Series'), ('6 Series', '6 Series'), ('7 Series', '7 Series'), ('8 Series', '8 Series'), ('X1', 'X1'), ('X2', 'X2'), ('X3', 'X3'), ('X4', 'X4'), ('X5', 'X5'), ('X6', 'X6'), ('X7', 'X7'), ('Z4', 'Z4'), ('i3', 'i3'), ('i8', 'i8')]), ('Bugatti', [('Chiron', 'Chiron'), ('Divo', 'Divo'), ('Veyron', 'Veyron')]), ('Buick', [('Enclave', 'Enclave'), ('Encore', 'Encore'), ('Envision', 'Envision'), ('Regal', 'Regal')]), ('Cadillac', [('ATS', 'ATS'), ('CT4', 'CT4'), ('CT5', 'CT5'), ('CT6', 'CT6'), ('Escalade', 'Escalade')]), ('Chevrolet', [('Camaro', 'Camaro'), ('Corvette', 'Corvette'), ('Impala', 'Impala'), ('Malibu', 'Malibu'), ('Silverado', 'Silverado')]), ('Chrysler', [('300', '300'), ('Pacifica', 'Pacifica')]), ('Citroën', [('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('Berlingo', 'Berlingo'), ('C3 Aircross', 'C3 Aircross')]), ('Dodge', [('Challenger', 'Challenger'), ('Charger', 'Charger'), ('Durango', 'Durango'), ('Journey', 'Journey')]), ('Ferrari', [('488', '488'), ('812', '812'), ('GTC4Lusso', 'GTC4Lusso'), ('Portofino', 'Portofino')]), ('Fiat', [('500', '500'), ('500X', '500X'), ('Panda', 'Panda'), ('Tipo', 'Tipo')]), ('Ford', [('Bronco', 'Bronco'), ('Escape', 'Escape'), ('Explorer', 'Explorer'), ('F-150', 'F-150'), ('Mustang', 'Mustang')]), ('Genesis', [('G70', 'G70'), ('G80', 'G80'), ('G90', 'G90')]), ('GMC', [('Acadia', 'Acadia'), ('Canyon', 'Canyon'), ('Sierra', 'Sierra'), ('Terrain', 'Terrain')]), ('Honda', [('Accord', 'Accord'), ('Civic', 'Civic'), ('CR-V', 'CR-V'), ('Pilot', 'Pilot')]), ('Hyundai', [('Elantra', 'Elantra'), ('Kona', 'Kona'), ('Palisade', 'Palisade'), ('Santa Fe', 'Santa Fe')]), ('Infiniti', [('Q50', 'Q50'), ('Q60', 'Q60'), ('QX50', 'QX50'), ('QX60', 'QX60')]), ('Jaguar', [('E-PACE', 'E-PACE'), ('F-PACE', 'F-PACE'), ('F-TYPE', 'F-TYPE'), ('XJ', 'XJ')]), ('Jeep', [('Cherokee', 'Cherokee'), ('Grand Cherokee', 'Grand Cherokee'), ('Renegade', 'Renegade'), ('Wrangler', 'Wrangler')]), ('Kia', [('Forte', 'Forte'), ('Sorento', 'Sorento'), ('Soul', 'Soul'), ('Telluride', 'Telluride')]), ('Lamborghini', [('Aventador', 'Aventador'), ('Huracan', 'Huracan'), ('Urus', 'Urus')]), ('Land Rover', [('Defender', 'Defender'), ('Discovery', 'Discovery'), ('Range Rover', 'Range Rover'), ('Range Rover Sport', 'Range Rover Sport')]), ('Lexus', [('ES', 'ES'), ('GX', 'GX'), ('LS', 'LS'), ('RX', 'RX')]), ('Lincoln', [('Aviator', 'Aviator'), ('Corsair', 'Corsair'), ('Navigator', 'Navigator')]), ('Lotus', [('Evora', 'Evora'), ('Exige', 'Exige')]), ('Maserati', [('Ghibli', 'Ghibli'), ('Levante', 'Levante'), ('Quattroporte', 'Quattroporte')]), ('Mazda', [('CX-5', 'CX-5'), ('CX-9', 'CX-9'), ('Mazda3', 'Mazda3'), ('Mazda6', 'Mazda6')]), ('McLaren', [('570S', '570S'), ('720S', '720S'), ('GT', 'GT')]), ('MINI', [('Clubman', 'Clubman'), ('Cooper', 'Cooper'), ('Countryman', 'Countryman')]), ('Mitsubishi', [('Eclipse Cross', 'Eclipse Cross'), ('Outlander', 'Outlander'), ('Pajero', 'Pajero')]), ('Nissan', [('Altima', 'Altima'), ('Maxima', 'Maxima'), ('Rogue', 'Rogue')]), ('Peugeot', [('2008', '2008'), ('3008', '3008'), ('5008', '5008')]), ('Porsche', [('911', '911'), ('Cayenne', 'Cayenne'), ('Macan', 'Macan')]), ('RAM', [('1500', '1500'), ('2500', '2500'), ('3500', '3500')]), ('Rolls-Royce', [('Cullinan', 'Cullinan'), ('Ghost', 'Ghost'), ('Phantom', 'Phantom')]), ('Saab', [('9-3', '9-3'), ('9-5', '9-5')]), ('Subaru', [('Ascent', 'Ascent'), ('Forester', 'Forester'), ('Outback', 'Outback')]), ('Suzuki', [('Jimny', 'Jimny'), ('Swift', 'Swift'), ('Vitara', 'Vitara')]), ('Tesla', [('Model 3', 'Model 3'), ('Model S', 'Model S'), ('Model X', 'Model X')]), ('Toyota', [('Camry', 'Camry'), ('Corolla', 'Corolla'), ('RAV4', 'RAV4')]), ('Volkswagen', [('Arteon', 'Arteon'), ('Golf', 'Golf'), ('Jetta', 'Jetta')]), ('Volvo', [('S60', 'S60'), ('S90', 'S90'), ('V60', 'V60'), ('XC40', 'XC40')])], max_length=100)),
                ('types', models.CharField(choices=[('For_rent', 'For Rent'), ('For_sell', 'For Sell')], default='', max_length=20)),
                ('categories', models.CharField(choices=[('Sedan', 'Sedan'), ('Jeep', 'Jeep'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Universal', 'Universal'), ('Cabriolet', 'Cabriolet'), ('Pickup', 'Pickup'), ('Minivan', 'Minivan'), ('Microbus', 'Microbus'), ('Limousine', 'Limousine')], default='', max_length=30)),
                ('price', models.IntegerField(default='0')),
                ('year', models.IntegerField(default='2024')),
                ('location', models.CharField(choices=[('Tbilisi', 'Tbilisi'), ('Kutaisi', 'Kutaisi'), ('Batumi', 'Batumi'), ('Rustavi', 'Rustavi'), ('Poti', 'Poti'), ('Zugdidi', 'Zugdidi'), ('Gori', 'Gori'), ('Samtredia', 'Samtredia'), ('Khashuri', 'Khashuri'), ('Tsentraluri', 'Tsentraluri'), ('Telavi', 'Telavi'), ('Ozurgeti', 'Ozurgeti'), ('Sendaqi', 'Sendaqi'), ('Borjomi', 'Borjomi'), ('Akhalkalaki', 'Akhalkalaki'), ('Akhaltsikhe', 'Akhaltsikhe'), ('Kobuleti', 'Kobuleti'), ('Tkibuli', 'Tkibuli'), ('Martvili', 'Martvili'), ('Kaspi', 'Kaspi'), ('Tsqaltubo', 'Tsqaltubo'), ('Khulo', 'Khulo'), ('Chiatura', 'Chiatura'), ('Sagarejo', 'Sagarejo'), ('Lagodekhi', 'Lagodekhi'), ('Dusheti', 'Dusheti'), ('Sachkhere', 'Sachkhere'), ('Kareli', 'Kareli'), ('Abasha', 'Abasha')], default='Tbilisi', max_length=40)),
                ('engine_volume', models.IntegerField(blank=True, default='0', null=True)),
                ('milage', models.IntegerField(default='0')),
                ('fuel_type', models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('LPG (Liquefied Petroleum Gas)', 'LPG (Liquefied Petroleum Gas)'), ('CNG (Compressed Natural Gas)', 'CNG (Compressed Natural Gas)'), ('Bioethanol', 'Bioethanol'), ('Hydrogen', 'Hydrogen')], default='Petrol', max_length=50, null=True)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('CVT (Continuously Variable Transmission)', 'CVT (Continuously Variable Transmission)'), ('DCT (Dual Clutch Transmission)', 'DCT (Dual Clutch Transmission)'), ('AMT (Automated Manual Transmission)', 'AMT (Automated Manual Transmission)'), ('Semi-automatic', 'Semi-automatic'), ('DSG (Direct-Shift Gearbox)', 'DSG (Direct-Shift Gearbox)'), ('Tiptronic', 'Tiptronic'), ('Torque Converter', 'Torque Converter'), ('Manumatic', 'Manumatic'), ('Sports Shift', 'Sports Shift')], default='Automatic', max_length=50)),
                ('cylinders', models.CharField(blank=True, choices=[(4, 4), (6, 6), (8, 8), (10, 10), (12, 12)], default='8', max_length=50, null=True)),
                ('doors', models.CharField(blank=True, choices=[(2, 2), (4, 4), (5, 5), ('More', 'More')], default='4', max_length=50, null=True)),
                ('drive_wheels', models.CharField(blank=True, choices=[('Front', 'Front'), ('Rear', 'Rear'), ('All-wheel drive', '4X4')], default='Rear', max_length=50, null=True)),
                ('wheel', models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right')], default='Left', max_length=50, null=True)),
                ('airbags', models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default='1', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_colors', models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Red', 'Red'), ('White', 'White'), ('Green', 'Green'), ('Brown', 'Brown'), ('Yellow', 'Yellow'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Gray', 'Gray')], default='Black', max_length=20)),
                ('interior', models.CharField(choices=[('Alcantara', 'Alcantara'), ('Artificial', 'Artificial'), ('Combined', 'Combined'), ('Leather', 'Leather'), ('Fabric', 'Fabric')], default='Alcantara', max_length=20)),
                ('interior_color', models.CharField(choices=[('Black', 'Black'), ('Red', 'Red'), ('White', 'White'), ('Brown', 'Brown'), ('Gray', 'Gray')], default='Black', max_length=20)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(to='cars.imagemodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
