# Generated by Django 5.0.3 on 2024-04-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
    ]
