# Generated by Django 5.0.3 on 2024-04-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(blank=True, choices=[('BMW', [('3 Series', '3 Series'), ('5 Series', '5 Series'), ('7 Series', '7 Series'), ('X1', 'X1'), ('X3', 'X3'), ('X5', 'X5'), ('X6', 'X6'), ('Z4', 'Z4')]), ('AUDI', [('A3', 'A3'), ('A4', 'A4'), ('A6', 'A6'), ('Q3', 'Q3'), ('Q5', 'Q5'), ('Q7', 'Q7')]), ('MERCEDES_BENZ', [('C-Class', 'C-Class'), ('E-Class', 'E-Class'), ('S-Class', 'S-Class'), ('GLA', 'GLA'), ('GLC', 'GLC'), ('GLE', 'GLE')])], max_length=100),
        ),
    ]
