# Generated by Django 5.0.3 on 2024-04-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_car_model'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='created_cars',
        ),
        migrations.AlterModelTable(
            name='imagemodel',
            table='uploaded_images',
        ),
    ]
