# Generated by Django 5.0.3 on 2024-04-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_table_alter_imagemodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='categories',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Suv', 'Suv'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Universal', 'Universal'), ('Cabriolet', 'Cabriolet'), ('Pickup', 'Pickup'), ('Minivan', 'Minivan'), ('Microbus', 'Microbus'), ('Limousine', 'Limousine')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='types',
            field=models.CharField(choices=[('For_sell', 'For Sell'), ('For_rent', 'For Rent')], default='', max_length=20),
        ),
    ]
