# Generated by Django 5.0.3 on 2024-04-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cylinders',
            field=models.CharField(blank=True, choices=[(4, 'Four cylinders'), (6, 'Six cylinders'), (8, 'Eight cylinders'), (10, 'Ten cylinders'), (12, 'Twelve cylinders')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_volume',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('LPG (Liquefied Petroleum Gas)', 'LPG (Liquefied Petroleum Gas)'), ('CNG (Compressed Natural Gas)', 'CNG (Compressed Natural Gas)'), ('Bioethanol', 'Bioethanol'), ('Hydrogen', 'Hydrogen')], default='Petrol', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='milage',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('CVT (Continuously Variable Transmission)', 'CVT (Continuously Variable Transmission)'), ('DCT (Dual Clutch Transmission)', 'DCT (Dual Clutch Transmission)'), ('AMT (Automated Manual Transmission)', 'AMT (Automated Manual Transmission)'), ('Semi-automatic', 'Semi-automatic'), ('DSG (Direct-Shift Gearbox)', 'DSG (Direct-Shift Gearbox)'), ('Tiptronic', 'Tiptronic'), ('Torque Converter', 'Torque Converter'), ('Manumatic', 'Manumatic'), ('Sports Shift', 'Sports Shift')], default='Automatic', max_length=50),
        ),
    ]
