# Generated by Django 5.0.3 on 2024-04-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_cylinders_car_engine_volume_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.CharField(blank=True, choices=[(2, 2), (4, 4), (5, 5), ('More', 'More')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='drive_wheels',
            field=models.CharField(blank=True, choices=[('Front', 'Front-wheel drive'), ('Rear', 'Rear-wheel drive'), ('All-wheel drive', '4X4')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='wheel',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='cylinders',
            field=models.CharField(blank=True, choices=[(4, 4), (6, 6), (8, 8), (10, 10), (12, 12)], default='', max_length=50, null=True),
        ),
    ]
