# Generated by Django 5.0.3 on 2024-04-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_doors_car_drive_wheels_car_wheel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='airbags',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_wheels',
            field=models.CharField(blank=True, choices=[('Front', 'Front'), ('Rear', 'Rear'), ('All-wheel drive', '4X4')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ManyToManyField(to='cars.imagemodel'),
        ),
    ]
