# Generated by Django 5.0.3 on 2024-04-21 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_imagemodel_car_airbags_alter_car_drive_wheels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='airbags',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='categories',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Jeep', 'Jeep'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Universal', 'Universal'), ('Cabriolet', 'Cabriolet'), ('Pickup', 'Pickup'), ('Minivan', 'Minivan'), ('Microbus', 'Microbus'), ('Limousine', 'Limousine')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='cylinders',
            field=models.CharField(blank=True, choices=[(4, 4), (6, 6), (8, 8), (10, 10), (12, 12)], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(blank=True, choices=[(2, 2), (4, 4), (5, 5), ('More', 'More')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_wheels',
            field=models.CharField(blank=True, choices=[('Front', 'Front'), ('Rear', 'Rear'), ('All-wheel drive', '4X4')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('LPG (Liquefied Petroleum Gas)', 'LPG (Liquefied Petroleum Gas)'), ('CNG (Compressed Natural Gas)', 'CNG (Compressed Natural Gas)'), ('Bioethanol', 'Bioethanol'), ('Hydrogen', 'Hydrogen')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(choices=[('Tbilisi', 'Tbilisi'), ('Kutaisi', 'Kutaisi'), ('Batumi', 'Batumi'), ('Rustavi', 'Rustavi'), ('Poti', 'Poti'), ('Zugdidi', 'Zugdidi'), ('Gori', 'Gori'), ('Samtredia', 'Samtredia'), ('Khashuri', 'Khashuri'), ('Tsentraluri', 'Tsentraluri'), ('Telavi', 'Telavi'), ('Ozurgeti', 'Ozurgeti'), ('Sendaqi', 'Sendaqi'), ('Borjomi', 'Borjomi'), ('Akhalkalaki', 'Akhalkalaki'), ('Akhaltsikhe', 'Akhaltsikhe'), ('Kobuleti', 'Kobuleti'), ('Tkibuli', 'Tkibuli'), ('Martvili', 'Martvili'), ('Kaspi', 'Kaspi'), ('Tsqaltubo', 'Tsqaltubo'), ('Khulo', 'Khulo'), ('Chiatura', 'Chiatura'), ('Sagarejo', 'Sagarejo'), ('Lagodekhi', 'Lagodekhi'), ('Dusheti', 'Dusheti'), ('Sachkhere', 'Sachkhere'), ('Kareli', 'Kareli'), ('Abasha', 'Abasha')], max_length=40),
        ),
        migrations.AlterField(
            model_name='car',
            name='milage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('CVT (Continuously Variable Transmission)', 'CVT (Continuously Variable Transmission)'), ('DCT (Dual Clutch Transmission)', 'DCT (Dual Clutch Transmission)'), ('AMT (Automated Manual Transmission)', 'AMT (Automated Manual Transmission)'), ('Semi-automatic', 'Semi-automatic'), ('DSG (Direct-Shift Gearbox)', 'DSG (Direct-Shift Gearbox)'), ('Tiptronic', 'Tiptronic'), ('Torque Converter', 'Torque Converter'), ('Manumatic', 'Manumatic'), ('Sports Shift', 'Sports Shift')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='types',
            field=models.CharField(choices=[('For_rent', 'For Rent'), ('For_sell', 'For Sell')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheel',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='cars.manufacturer'),
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.manufacturer'),
        ),
    ]
