# Generated by Django 5.0.3 on 2024-04-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_car_car_model_alter_car_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_colors',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Red', 'Red'), ('White', 'White'), ('Green', 'Green'), ('Brown', 'Brown'), ('Yellow', 'Yellow'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Gray', 'Gray')], default='Black', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='interior',
            field=models.CharField(choices=[('Alcantara', 'Alcantara'), ('Artificial', 'Artificial'), ('Combined', 'Combined'), ('Leather', 'Leather'), ('Fabric', 'Fabric')], default='Black', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='interior_color',
            field=models.CharField(choices=[('Black', 'Black'), ('Red', 'Red'), ('White', 'White'), ('Brown', 'Brown'), ('Gray', 'Gray')], default='Black', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='airbags',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default='1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='cylinders',
            field=models.CharField(blank=True, choices=[(4, 4), (6, 6), (8, 8), (10, 10), (12, 12)], default='8', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(blank=True, choices=[(2, 2), (4, 4), (5, 5), ('More', 'More')], default='4', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_wheels',
            field=models.CharField(blank=True, choices=[('Front', 'Front'), ('Rear', 'Rear'), ('All-wheel drive', '4X4')], default='Rear', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheel',
            field=models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right')], default='Left', max_length=50, null=True),
        ),
    ]
